
# Use %player% to tag a player #

###########################
#       Permissions       #
###########################
ChatManage: 'chat.manage'
HelpOpSee: 'helpop.see'
ChatBypass: 'chat.bypass'

###########################
#         Messages        #
###########################
ChatIsOn: '&9The is already turned &bon'
ChatIsOff: '&9The is already turned &boff'
ChatOff: '&9The chat was turned &boff &9by &b%player%'
ChatOn: '&9The chat was turned &bon &9by &b%player%'
ChatClear: '&9The chat was &bCleared &9by &b%player%'
ChatBlocked: '&9The chat is currently blocked!'
ChatPerm: '&9You dont have permissions to use this command!'
HelpOp: '&8[&c&lHelp&4&lOP&8] &7%player% &8>> &7'
HelpOpEmpty: '&9Helpop message cant be empty!'
HelpOpSent: '&9Your message is successfully sent'
ChatEmpty: '&9Use : &b/chat cc/on/off'
IllegalMessage: '&9Your message cant been sent because have a illegal words!'

###########################
#       BlockedWords      #
###########################
BlockedWords:
    - 'wrongword1'
    - 'wrongword2'